name: Export Webflow CMS to JSON

on:
  workflow_dispatch:        # allow manual run
  schedule:
    - cron: "0 0 * * *"     # every day at 00:00 UTC

jobs:
  export-cms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch CMS data from Webflow
        run: |
          node -e "
          const fs = require('fs');

          (async () => {
            const url = 'https://api.webflow.com/v2/collections/68933f50454777c4b8afb247/items';
            let items = [];
            let offset = 0;
            const limit = 100;

            while (true) {
              const res = await fetch(\`\${url}?offset=\${offset}&limit=\${limit}\`, {
                headers: {
                  'Authorization': 'Bearer ' + process.env.WEBFLOW_API_SITE_TOKEN,
                  'accept': 'application/json'
                }
              });
              const data = await res.json();
              if (!data.items || data.items.length === 0) break;
              items = items.concat(data.items);
              if (data.items.length < limit) break;
              offset += limit;
            }

            // Map only the fields we care about
            const simplified = items.map(i => ({
              name: i.fieldData.name,
              slug: i.fieldData.slug,
              price: i.fieldData['price'],
              affiliateLink: i.fieldData['affiliate-link'],
              description: i.fieldData.description,
              tempImage: i.fieldData['temp-image']
            }));

            fs.writeFileSync('affiliate_products.json', JSON.stringify(simplified, null, 2));
          })();
          "
        env:
          WEBFLOW_API_SITE_TOKEN: ${{ secrets.WEBFLOW_API_SITE_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add affiliate_products.json
          git commit -m "Auto-update affiliate_products.json from Webflow CMS" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}